// Agent Component Renderer - Renders UI components generated by agents
import React from "react";

/**
 * Renders a single component generated by the agent system
 * Supported types: Table, Chart, PropertyPanel, Card, Alert
 */
export default function AgentComponentRenderer({ component }) {
  if (!component || !component.type) return null;

  switch (component.type) {
    case "Table":
      return <TableComponent data={component.data} />;
    case "Chart":
      return <ChartComponent data={component.data} />;
    case "PropertyPanel":
      return <PropertyPanelComponent data={component.data} />;
    case "Card":
      return <CardComponent data={component.data} />;
    case "Alert":
      return <AlertComponent data={component.data} />;
    default:
      return <div style={{ color: "#ef4444" }}>Unknown component type: {component.type}</div>;
  }
}

// Table Component
function TableComponent({ data }) {
  const { columns = [], rows = [], title } = data;

  return (
    <div style={{ marginTop: "1rem" }}>
      {title && <h4 style={{ marginBottom: "0.75rem", fontSize: "1rem", fontWeight: 600 }}>{title}</h4>}
      <div style={{ overflowX: "auto", border: "1px solid #e5e7eb", borderRadius: "0.375rem" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.875rem" }}>
          <thead style={{ backgroundColor: "#f9fafb" }}>
            <tr>
              {columns.map((col, idx) => (
                <th key={idx} style={{
                  padding: "0.75rem",
                  textAlign: "left",
                  fontWeight: 600,
                  borderBottom: "1px solid #e5e7eb"
                }}>
                  {col}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, rowIdx) => (
              <tr key={rowIdx} style={{ borderBottom: "1px solid #f3f4f6" }}>
                {row.map((cell, cellIdx) => (
                  <td key={cellIdx} style={{ padding: "0.75rem" }}>
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// Chart Component (Simple bar chart)
function ChartComponent({ data }) {
  const { title, labels = [], values = [] } = data;
  const maxValue = Math.max(...values);

  return (
    <div style={{ marginTop: "1rem" }}>
      {title && <h4 style={{ marginBottom: "0.75rem", fontSize: "1rem", fontWeight: 600 }}>{title}</h4>}
      <div style={{ padding: "1rem", backgroundColor: "#f9fafb", borderRadius: "0.375rem" }}>
        {labels.map((label, idx) => {
          const value = values[idx] || 0;
          const percentage = maxValue > 0 ? (value / maxValue) * 100 : 0;
          
          return (
            <div key={idx} style={{ marginBottom: "0.75rem" }}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "0.25rem", fontSize: "0.875rem" }}>
                <span>{label}</span>
                <span style={{ fontWeight: 600 }}>{value}</span>
              </div>
              <div style={{
                width: "100%",
                height: "1.5rem",
                backgroundColor: "#e5e7eb",
                borderRadius: "0.25rem",
                overflow: "hidden"
              }}>
                <div style={{
                  width: `${percentage}%`,
                  height: "100%",
                  backgroundColor: "#3b82f6",
                  transition: "width 0.3s ease",
                  display: "flex",
                  alignItems: "center",
                  paddingLeft: "0.5rem",
                  color: "white",
                  fontSize: "0.75rem"
                }}>
                  {percentage > 10 && `${Math.round(percentage)}%`}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// Property Panel Component
function PropertyPanelComponent({ data }) {
  const { title, properties = {} } = data;

  return (
    <div style={{ marginTop: "1rem" }}>
      {title && <h4 style={{ marginBottom: "0.75rem", fontSize: "1rem", fontWeight: 600 }}>{title}</h4>}
      <div style={{
        padding: "1rem",
        backgroundColor: "#f9fafb",
        border: "1px solid #e5e7eb",
        borderRadius: "0.375rem"
      }}>
        {Object.entries(properties).map(([key, value], idx) => (
          <div key={idx} style={{
            display: "flex",
            justifyContent: "space-between",
            padding: "0.5rem 0",
            borderBottom: idx < Object.entries(properties).length - 1 ? "1px solid #e5e7eb" : "none",
            fontSize: "0.875rem"
          }}>
            <span style={{ color: "#6b7280", fontWeight: 500 }}>{key}:</span>
            <span style={{ fontWeight: 600 }}>{String(value)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// Card Component
function CardComponent({ data }) {
  const { title, content, icon, color = "#3b82f6" } = data;

  return (
    <div style={{
      marginTop: "1rem",
      padding: "1rem",
      backgroundColor: "#ffffff",
      border: `2px solid ${color}`,
      borderRadius: "0.5rem",
      boxShadow: "0 1px 3px rgba(0,0,0,0.1)"
    }}>
      <div style={{ display: "flex", alignItems: "start", gap: "0.75rem" }}>
        {icon && (
          <div style={{
            width: "2.5rem",
            height: "2.5rem",
            backgroundColor: color,
            color: "white",
            borderRadius: "0.375rem",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "1.25rem"
          }}>
            {icon}
          </div>
        )}
        <div style={{ flex: 1 }}>
          {title && <h4 style={{ margin: "0 0 0.5rem 0", fontSize: "1rem", fontWeight: 600 }}>{title}</h4>}
          <p style={{ margin: 0, fontSize: "0.875rem", color: "#4b5563", lineHeight: "1.5" }}>{content}</p>
        </div>
      </div>
    </div>
  );
}

// Alert Component
function AlertComponent({ data }) {
  const { message, type = "info" } = data;
  
  const styles = {
    info: { bg: "#eff6ff", border: "#3b82f6", text: "#1e40af" },
    success: { bg: "#f0fdf4", border: "#10b981", text: "#065f46" },
    warning: { bg: "#fef3c7", border: "#f59e0b", text: "#92400e" },
    error: { bg: "#fee2e2", border: "#ef4444", text: "#991b1b" },
  };
  
  const style = styles[type] || styles.info;
  
  const icons = {
    info: "ℹ️",
    success: "✅",
    warning: "⚠️",
    error: "❌",
  };

  return (
    <div style={{
      marginTop: "1rem",
      padding: "0.75rem 1rem",
      backgroundColor: style.bg,
      border: `1px solid ${style.border}`,
      borderRadius: "0.375rem",
      display: "flex",
      alignItems: "center",
      gap: "0.75rem",
      fontSize: "0.875rem",
      color: style.text
    }}>
      <span style={{ fontSize: "1.25rem" }}>{icons[type]}</span>
      <span>{message}</span>
    </div>
  );
}
